FROM python:3.12-slim

WORKDIR /

COPY requirements_old.txt ./

RUN pip install --no-cache-dir -r requirements_old.txt

RUN apt-get update && apt-get install -y apt-utils

COPY . .

CMD ["python", "app/bot_old.py"]